import type { VisualWorkbench } from "@/lib/types";
import type { VisualPlan, VisualRecord } from "@/lib/product-intelligence/visual-schemas";
import { productImage } from "@/lib/mock/images";
const uuid = (n: number) => `00000000-0000-4000-8000-${String(n).padStart(12, "0")}`;
const hash = "a".repeat(64), now = "2026-10-07T12:00:00Z", current = { state: "current" as const, reasons: [] };
export function fixture(stale = false): VisualWorkbench {
  const changed = { state: "needs_review" as const, reasons: [{ code: "dependency_changed", dependency_key: "identity:base", message: "La referencia cambió. Revisa la fidelidad al producto antes de usar la pieza." }] };
  const record = (n: number, kind: VisualRecord["kind"], payload: Record<string, unknown>, status: string): VisualWorkbench["records"][number] => ({ id: uuid(n), kind, version: 1, etag: hash, status, payload, created_at: now, updated_at: now, validity: current, reviews: [] });
  const identity = record(2, "identity", { canonical_reference_image_id: uuid(3), reference_content_hash: hash, reference_mode: "strict_product_identity", identity_description: "Organizador rectangular con compartimentos", preserve: ["Silueta", "Compartimentos", "Proporciones"], allowed_variations: ["Ángulo de cámara", "Entorno", "Iluminación"], forbidden_variations: ["Cambiar la forma", "Inventar accesorios"], dependencies: [], identity_hash: hash }, "approved");
  const p: VisualPlan = { name: "Fotos de la página", strategy_id: uuid(4), identity_ref: { id: identity.id, version: identity.version, etag: hash }, visual_system: { world: "real_home", palette: "Neutros", lighting: "Luz natural", photography_style: "Fotografía realista", typography: null, mood: "Práctico", consistency_notes: "Mismo escritorio y luz en todas las tomas" }, shots: [
    { shot_key: "desktop_hero", shot_family: "product_clarity", name: "Organizador en el escritorio", priority: "must_have", channel: "pdp", angle_id: uuid(5), landing_angle_id: null, landing_hook_id: null, persuasion_plan_ref: null, section_key: null, persuasion_job: "recognition", belief_keys: [], fact_ids: [], evidence_ids: [], claim_keys: [], objective: "Mostrar cómo encuentra lugar cada útil de escritorio", product_identity: "inherit", product_role: "hero", representation: "product_depiction", scene: { environment: "Hogar", location: "Escritorio", surface: "Madera", action: "El organizador contiene lápices y útiles cotidianos", props: ["Lápices"], lighting: "Ventana lateral", result: null, people: { allowed: false, face_visible: false, description: null } }, composition: { aspect_ratio: "1:1", camera: "Tres cuartos", framing: "Plano medio", product_prominence: "hero", negative_space: null, focus: "Compartimentos" }, message: { takeaway: "Cada útil tiene su espacio", overlay_text: null }, avoid: ["Desorden artificial extremo"], generation_required: true }
  ] };
  const plan = record(6, "plan", p as unknown as Record<string, unknown>, "approved"); plan.validity = stale ? changed : current; plan.shot_validity = { desktop_hero: plan.validity };
  const first = record(7, "asset", { file_id: uuid(8), plan_ref: { id: plan.id, version: 1, etag: hash }, identity_ref: p.identity_ref, shot_key: "desktop_hero", shot_family: "product_clarity", source_system: "chatgpt", representation: "product_depiction", dependencies: [] }, "approved");
  first.file = { url: productImage(1, 1), width: 1000, height: 1000, mime_type: "image/webp", size_bytes: 24000 }; first.validity = stale ? changed : current;
  const second = { ...first, id: uuid(9), status: "generated", validity: current, file: { ...first.file, url: productImage(2, 1) } };
  const review = record(10, "review", { subject_id: first.id, decision: "approve", reason: "Mantiene la forma y muestra bien los compartimentos", tags: ["good_product_fidelity"] }, "recorded"); first.reviews = [review];
  const target = { type: "gallery_shot" as const, shot_key: "desktop_hero", slot: "cover", position: null };
  const binding = record(11, "binding", { asset_id: first.id, target, target_key: "gallery:cover", target_etag: hash, dependencies: [] }, "selected"); binding.validity = first.validity;
  return { product_id: uuid(1), revision: 10, etag: hash, dependency_stamp: hash, canonical_reference: { id: uuid(3), content_hash: hash, url: productImage(1, 1) }, records: [identity, plan, first, second, review, binding], targets: [{ key: "gallery:cover", etag: hash, target }], asset_offset: 0, asset_total: 2 };
}
